---

- name: add the apt keys for postgresql provided DEBs
  sudo: True
  apt_key: id=ACCC4CF8 state=present 
           data="{{ lookup('file', 'apt.postgresql.org_key_ACCC4CF8.asc' ) }}"


- name: add the apt source repo for postgresql DEBs
  sudo: True
  register: add_pg_apt_result
  apt_repository: 
   repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

- name: update apt after adding postgresql source
  sudo: True
  apt: update_cache=yes
  when: add_pg_apt_result.changed

# TODO FIXME: install this from source instead of binary
# don't trust upstream binaries.

- name: install postgres client
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-client-{{pg_ver}}
    - libpq-dev

- name: install postgres server
  sudo: True
  apt: pkg={{ item }} state=present
  when: pg_server
  with_items:
    - postgresql-{{pg_ver}}
    - postgresql-plpython-{{pg_ver}}
    - postgresql-plperl-{{pg_ver}}
    - postgresql-contrib-{{pg_ver}}
    - postgresql-server-dev-{{pg_ver}}

- name: change ownership of postgres directory
  sudo: True
  when: pg_server
  file: path=/var/lib/postgresql state=directory
    owner=postgres group=postgres mode=0700

- name: create main pg cluster
  sudo: True
  when: pg_server
  tags: pg_createcluster
  command: pg_createcluster {{ pg_ver }} main --start
    creates=/var/lib/postgresql/{{ pg_ver }}/main

- name: increase shared memory allowances
  sudo: True
  when: pg_server
  template: src=postgresql-shm.conf.j2
            dest=/etc/sysctl.d/30-postgresql-shm.conf
            owner=root group=root mode=644
  notify: sysctl update

- meta: flush_handlers

- name: write postgresql.conf file
  tags: pgconf
  when: pg_server
  sudo: True
  template: src=postgresql.conf.j2
            dest="/etc/postgresql/{{pg_ver}}/main/postgresql.conf"
            owner=postgres group=postgres mode=644
  notify: reload postgres
  register: pg_conf_rewritten

- name: start postgresql
  sudo: True
  service: name=postgresql state=started
  when: pg_server

- name: restart postgres in dev when pg conf rewritten
  tags: pgconf
  when: pg_conf_rewritten.changed and development
  sudo: True
  service: name=postgresql state=restarted

- name: write postgres log rotate conf file
  tags: pglogconf
  when: pg_server
  sudo: True
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/postgresql-common
            owner=root group=root mode=644 

- name: write postgresql hba conf file
  sudo: True
  tags: pgconf
  template: src=roles/postgresql/templates/pg_hba.conf.j2
            dest="/etc/postgresql/{{pg_ver}}/main/pg_hba.conf"
            owner=postgres group=postgres mode=640
  notify: reload postgres

- name: get pg restarted
  meta: flush_handlers

